
import { ThemeProvider } from '@/components/theme-provider'
import './globals.css'
import { Toaster } from 'sonner';
import { Inter } from 'next/font/google'
import { Navbar } from '@/components/navbar'
import BackButtonNavigation from '@/components/ui/back';
import { Analytics } from '@vercel/analytics/react';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Bloggs',
  description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
 
  
  return (
    <html lang="en" suppressHydrationWarning>
       <body className={`${inter.className} `}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <Navbar/>
          <BackButtonNavigation/>
           <div className='mt-24 p-4 pt-24'> {children}</div>
            <Toaster />
          </ThemeProvider>
          <Analytics />
        </body>
    </html>
  )
}
